spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://example.org
          predicates:
            # 对应 AfterRoutePredicateFactory
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Before=2027-01-20T17:42:47.789-07:00[America/Denver]
            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2027-01-20T17:42:47.789-07:00[America/Denver]
# 直接浏览器访问 http://127.0.0.1:8080