spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org
          predicates:
            - Method=GET
# curl localhost:8080
# curl -X POST localhost:8080 请求错误405